import { useCallback } from "react";
import { Wallet, TrendingUp } from "lucide-react";
import { useCurrentUser } from "@/lib/auth";
import { supabase } from "@/lib/supabase";
import { useAsync } from "@/lib/use-async";
import { formatCurrency, formatMonth } from "@/lib/format";
import { StatCard } from "@/components/stat-card";
import { PageState } from "@/components/page-state";
import { PayslipTable } from "@/components/payroll/payslip-table";
import { PayrollAdminTable } from "@/components/payroll/payroll-admin-table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function PayrollPage() {
  const user = useCurrentUser();
  const isAdmin = user.role === "ADMIN";

  const load = useCallback(async () => {
    const [mine, team] = await Promise.all([
      supabase
        .from("payslips")
        .select("*")
        .eq("user_id", user.id)
        .order("month", { ascending: false }),
      isAdmin
        ? supabase
            .from("payslips")
            .select("*, user:profiles(id, name, department, job_title)")
            .order("month", { ascending: false })
        : Promise.resolve({ data: [], error: null }),
    ]);
    if (mine.error) throw mine.error;
    if (team.error) throw team.error;
    return { myPayslips: mine.data, allPayslips: team.data ?? [] };
  }, [user, isAdmin]);

  const { data, error } = useAsync(load);
  const latest = data?.myPayslips[0];

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Payroll</h1>
        <p className="mt-1 text-muted-foreground">
          Review your monthly payslips and salary breakdown.
        </p>
      </div>

      {latest && (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <StatCard
            icon={Wallet}
            label={`Latest net pay (${formatMonth(latest.month)})`}
            value={formatCurrency(latest.net_pay)}
            hint={`Basic ${formatCurrency(latest.basic_salary)} + allowances ${formatCurrency(latest.allowances)}`}
          />
          <StatCard
            icon={TrendingUp}
            label="Payslips on record"
            value={String(data.myPayslips.length)}
            hint="Generated by HR each month"
          />
        </div>
      )}

      {!data ? (
        <PageState error={error} />
      ) : isAdmin ? (
        <Tabs defaultValue="mine">
          <TabsList>
            <TabsTrigger value="mine">My Payroll</TabsTrigger>
            <TabsTrigger value="team">All Employees</TabsTrigger>
          </TabsList>
          <TabsContent value="mine" className="mt-4">
            <PayslipTable payslips={data.myPayslips} />
          </TabsContent>
          <TabsContent value="team" className="mt-4">
            <PayrollAdminTable payslips={data.allPayslips} />
          </TabsContent>
        </Tabs>
      ) : (
        <PayslipTable payslips={data.myPayslips} />
      )}
    </div>
  );
}
